### ISSUE TITLE
공유 메모리 접근키 암호화

### ISSUE THREAD

**Issue by nusgnojkrap** [A-big-fish-in-a-small-pond/Express-Concurrent-Control#10]
현재 client IP 를 공유 메모리 접근키로 사용 중인 부분 암호화

**Comment by libtv** [comment]
음.. 아마도 공유메모리나 레디스에 접근할 때의 키를 암호화하려는 것 같습니다. 
암호화 과정은 Decryption 이 필요하지 않지만.. 
필요하다고 하는 클라이언트를 제공하기 위해 과정을 설명하겠습니다.



-----------------------------------
1. 키 생성 : md5 
2. aes-256 암호화
-----------------------------------

과정을 수행하겠습니다.

**Comment by libtv** [comment]
Issue Complete
